import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { Plugin, ViteDevServer } from "vite";

const root = path.dirname(fileURLToPath(import.meta.url));
const FLEET_DIR = path.resolve(root, "public/fleet");
const GENERATED = path.resolve(root, "src/data/fleet.generated.ts");
const MEDIA = /\.(mp4|webm|mov|m4v|jpe?g|png|webp|avif|gif)$/i;

function walk(dir: string, rel = ""): string[] {
  if (!fs.existsSync(dir)) return [];
  const out: string[] = [];
  for (const name of fs.readdirSync(dir)) {
    if (name.startsWith(".")) continue;
    if (name === "README.md" || name === "manifest.json") continue;
    const full = path.join(dir, name);
    const nested = rel ? `${rel}/${name}` : name;
    const stat = fs.statSync(full);
    if (stat.isDirectory()) out.push(...walk(full, nested));
    else if (MEDIA.test(name)) out.push(`/fleet/${nested}`);
  }
  return out.sort();
}

export function writeFleetGenerated() {
  const files = walk(FLEET_DIR);
  const body =
    `/** Auto-generated by vite-plugin-fleet. Do not edit. */\n` +
    `export const FLEET_FILES: readonly string[] = ${JSON.stringify(files, null, 2)};\n`;
  const prev = fs.existsSync(GENERATED) ? fs.readFileSync(GENERATED, "utf8") : "";
  if (prev !== body) fs.writeFileSync(GENERATED, body);
  return files;
}

function reloadGenerated(server: ViteDevServer) {
  const mods = server.moduleGraph.getModulesByFile(GENERATED);
  mods?.forEach((mod) => {
    void server.reloadModule(mod);
  });
}

export function fleetPlugin(): Plugin {
  return {
    name: "fleet-manifest",
    buildStart() {
      writeFleetGenerated();
    },
    configureServer(server) {
      writeFleetGenerated();
      server.watcher.add(FLEET_DIR);
      const regen = (file: string) => {
        const normalized = file.replaceAll("\\", "/");
        if (!normalized.includes("/public/fleet")) return;
        writeFleetGenerated();
        reloadGenerated(server);
      };
      server.watcher.on("add", regen);
      server.watcher.on("unlink", regen);
      server.watcher.on("change", regen);
    },
  };
}
