/**
 * Trip Concierge client.
 *
 * - Edge mode: when VITE_SUPABASE_URL + VITE_SUPABASE_ANON_KEY are set, the
 *   itinerary is generated by the LLM-backed Supabase Edge Function
 *   (supabase/functions/trip-concierge).
 * - Local mode (default, and the fallback on ANY edge/network failure):
 *   a deterministic generator with curated data for popular Egypt driving
 *   routes plus a generic template for unknown routes. Fully bilingual.
 */

export type ConciergeLanguage = "en" | "ar";

export interface ItineraryStop {
  time: string;
  name: string;
  note: string;
}

export interface ItineraryDay {
  day: number;
  title: string;
  stops: ItineraryStop[];
}

export interface Itinerary {
  days: ItineraryDay[];
  tips: string[];
}

export interface TripPlanRequest {
  car: { name: string; type: string; seats: number };
  startDate: string;
  endDate: string;
  from: string;
  to: string;
  language: ConciergeLanguage;
}

export interface TripPlanResult {
  itinerary: Itinerary;
  /** "edge" = LLM via Supabase Edge Function, "local" = built-in generator. */
  source: "edge" | "local";
}

/* ------------------------------------------------------------------ */
/* Destinations offered in the picker                                  */
/* ------------------------------------------------------------------ */

interface Localized {
  en: string;
  ar: string;
}

export interface ConciergeDestination {
  id: string;
  name: Localized;
}

export const DESTINATIONS: ConciergeDestination[] = [
  { id: "north-coast", name: { en: "North Coast", ar: "الساحل الشمالي" } },
  { id: "alexandria", name: { en: "Alexandria", ar: "الإسكندرية" } },
  { id: "ain-sokhna", name: { en: "Ain Sokhna", ar: "العين السخنة" } },
  { id: "fayoum", name: { en: "Fayoum", ar: "الفيوم" } },
  { id: "hurghada", name: { en: "Hurghada", ar: "الغردقة" } },
  { id: "luxor", name: { en: "Luxor", ar: "الأقصر" } },
];

export function destinationLabel(id: string, language: ConciergeLanguage): string {
  const d = DESTINATIONS.find((x) => x.id === id);
  return d ? d.name[language] : id;
}

/* ------------------------------------------------------------------ */
/* Local route data                                                    */
/* ------------------------------------------------------------------ */

interface StopDef {
  time: string;
  name: Localized;
  note: Localized;
}

interface RouteDef {
  outboundTitle: Localized;
  exploreTitle: Localized;
  returnTitle: Localized;
  outbound: StopDef[];
  explore: StopDef[];
  inbound: StopDef[];
  tips: Localized[];
}

const SHARED_TIPS: Localized[] = [
  {
    en: "Keep your license, rental contract, and ID handy — highway checkpoints are routine.",
    ar: "احتفظ برخصتك وعقد الإيجار وبطاقة الهوية في متناول يدك — نقاط التفتيش على الطرق السريعة أمر معتاد.",
  },
  {
    en: "Fuel up before long desert stretches; stations can be 100+ km apart.",
    ar: "املأ خزان الوقود قبل المسافات الصحراوية الطويلة؛ قد تبعد المحطات أكثر من ١٠٠ كم عن بعضها.",
  },
  {
    en: "Avoid driving after dark outside the cities — lighting and lane markings are poor.",
    ar: "تجنب القيادة بعد حلول الظلام خارج المدن — الإضاءة وعلامات الطريق ضعيفة.",
  },
  {
    en: "Carry small cash for road tolls and parking attendants.",
    ar: "احمل نقودًا صغيرة لرسوم الطرق وعمال مواقف السيارات.",
  },
];

const ROUTES: Record<string, RouteDef> = {
  "cairo>north-coast": {
    outboundTitle: { en: "Cairo to the North Coast", ar: "من القاهرة إلى الساحل الشمالي" },
    exploreTitle: { en: "A day on the North Coast", ar: "يوم على الساحل الشمالي" },
    returnTitle: { en: "Back to Cairo", ar: "العودة إلى القاهرة" },
    outbound: [
      {
        time: "07:30",
        name: { en: "Fuel up in Sheikh Zayed", ar: "التزود بالوقود في الشيخ زايد" },
        note: {
          en: "Full tank before the Cairo–Alamein desert road; ~4.5h total drive.",
          ar: "خزان ممتلئ قبل طريق القاهرة–العلمين الصحراوي؛ إجمالي القيادة حوالي ٤٫٥ ساعات.",
        },
      },
      {
        time: "09:30",
        name: { en: "Wadi El Natrun rest stop", ar: "استراحة وادي النطرون" },
        note: {
          en: "Coffee and restrooms; last big service area before the coast.",
          ar: "قهوة ودورات مياه؛ آخر منطقة خدمات كبيرة قبل الساحل.",
        },
      },
      {
        time: "11:30",
        name: { en: "El Alamein War Museum", ar: "متحف العلمين الحربي" },
        note: {
          en: "A 45-minute stop at the WWII battlefield memorial.",
          ar: "توقف لمدة ٤٥ دقيقة عند النصب التذكاري لمعركة الحرب العالمية الثانية.",
        },
      },
      {
        time: "13:00",
        name: { en: "Lunch at Sidi Abdel Rahman", ar: "غداء في سيدي عبد الرحمن" },
        note: {
          en: "Seafront lunch; the lagoon-blue water starts here.",
          ar: "غداء على الواجهة البحرية؛ من هنا تبدأ المياه الفيروزية.",
        },
      },
      {
        time: "14:30",
        name: { en: "Check in and beach time", ar: "تسجيل الوصول ووقت الشاطئ" },
        note: {
          en: "Settle in and catch the late-afternoon sea breeze.",
          ar: "استقر في مكان إقامتك واستمتع بنسيم البحر في العصر.",
        },
      },
    ],
    explore: [
      {
        time: "10:00",
        name: { en: "Morning swim", ar: "سباحة صباحية" },
        note: {
          en: "The Mediterranean is calmest before noon.",
          ar: "البحر المتوسط أهدأ ما يكون قبل الظهيرة.",
        },
      },
      {
        time: "13:00",
        name: { en: "Marassi or Marina promenade", ar: "ممشى مراسي أو مارينا" },
        note: {
          en: "Lunch, shops, and yacht views along the marina.",
          ar: "غداء ومحلات وإطلالات على اليخوت بطول المارينا.",
        },
      },
      {
        time: "17:00",
        name: { en: "New Alamein towers drive", ar: "جولة بالسيارة في أبراج العلمين الجديدة" },
        note: {
          en: "A short scenic drive through the new coastal city.",
          ar: "جولة قصيرة ممتعة بالسيارة في المدينة الساحلية الجديدة.",
        },
      },
      {
        time: "19:30",
        name: { en: "Sunset dinner by the lagoon", ar: "عشاء وقت الغروب على البحيرة" },
        note: {
          en: "Book ahead in summer — coastal restaurants fill up fast.",
          ar: "احجز مسبقًا في الصيف — مطاعم الساحل تمتلئ بسرعة.",
        },
      },
    ],
    inbound: [
      {
        time: "11:00",
        name: { en: "Late checkout and fuel", ar: "مغادرة متأخرة وتزود بالوقود" },
        note: {
          en: "Top up before leaving the coast strip.",
          ar: "املأ الخزان قبل مغادرة شريط الساحل.",
        },
      },
      {
        time: "13:30",
        name: { en: "Wadi El Natrun break", ar: "استراحة وادي النطرون" },
        note: {
          en: "Stretch your legs at the halfway point.",
          ar: "استرح قليلًا عند منتصف الطريق.",
        },
      },
      {
        time: "16:00",
        name: { en: "Arrive Cairo", ar: "الوصول إلى القاهرة" },
        note: {
          en: "Time the arrival to dodge the 5–8pm ring road rush.",
          ar: "خطط للوصول قبل زحام الطريق الدائري بين ٥ و٨ مساءً.",
        },
      },
    ],
    tips: [
      {
        en: "Summer Fridays are the busiest on the Alamein road — leave before 8am.",
        ar: "أيام الجمعة في الصيف هي الأكثر ازدحامًا على طريق العلمين — انطلق قبل الثامنة صباحًا.",
      },
      ...SHARED_TIPS.slice(0, 3),
    ],
  },

  "cairo>alexandria": {
    outboundTitle: { en: "Cairo to Alexandria", ar: "من القاهرة إلى الإسكندرية" },
    exploreTitle: { en: "A day in Alexandria", ar: "يوم في الإسكندرية" },
    returnTitle: { en: "Back to Cairo", ar: "العودة إلى القاهرة" },
    outbound: [
      {
        time: "08:00",
        name: { en: "Depart via the Desert Road", ar: "الانطلاق عبر الطريق الصحراوي" },
        note: {
          en: "Cairo–Alex desert road, ~2.5–3h with one stop.",
          ar: "طريق القاهرة–الإسكندرية الصحراوي، حوالي ساعتين ونصف إلى ثلاث ساعات مع توقف واحد.",
        },
      },
      {
        time: "09:30",
        name: { en: "Wadi El Natrun rest house", ar: "استراحة وادي النطرون" },
        note: {
          en: "Quick coffee; the monasteries are a worthy detour if you have time.",
          ar: "قهوة سريعة؛ الأديرة تستحق الزيارة إن كان لديك وقت.",
        },
      },
      {
        time: "11:30",
        name: { en: "Qaitbay Citadel", ar: "قلعة قايتباي" },
        note: {
          en: "Park along the eastern harbour and walk the sea wall.",
          ar: "اركن السيارة عند الميناء الشرقي وامشِ على سور البحر.",
        },
      },
      {
        time: "13:30",
        name: { en: "Seafood lunch in Bahari", ar: "غداء سمك في بحري" },
        note: {
          en: "Pick your fish at the counter — the local way.",
          ar: "اختر سمكك من الثلاجة — على الطريقة السكندرية.",
        },
      },
      {
        time: "16:00",
        name: { en: "Bibliotheca Alexandrina", ar: "مكتبة الإسكندرية" },
        note: {
          en: "An hour inside, then a Corniche sunset drive.",
          ar: "ساعة بالداخل ثم جولة غروب بالسيارة على الكورنيش.",
        },
      },
    ],
    explore: [
      {
        time: "10:00",
        name: { en: "Montaza Palace gardens", ar: "حدائق قصر المنتزه" },
        note: {
          en: "Morning walk under the palms by the royal palace.",
          ar: "نزهة صباحية بين النخيل بجوار القصر الملكي.",
        },
      },
      {
        time: "13:00",
        name: { en: "Catacombs of Kom El Shoqafa", ar: "مقابر كوم الشقافة" },
        note: {
          en: "Roman-era underground tombs; cool escape from midday heat.",
          ar: "مقابر رومانية تحت الأرض؛ ملاذ بارد من حر الظهيرة.",
        },
      },
      {
        time: "17:00",
        name: { en: "Stanley Bridge at golden hour", ar: "كوبري ستانلي وقت الغروب" },
        note: {
          en: "The classic Alexandria photo stop.",
          ar: "أشهر مكان لالتقاط الصور في الإسكندرية.",
        },
      },
    ],
    inbound: [
      {
        time: "12:00",
        name: { en: "Brunch on the Corniche", ar: "فطور متأخر على الكورنيش" },
        note: {
          en: "One last sea view before the drive back.",
          ar: "إطلالة أخيرة على البحر قبل رحلة العودة.",
        },
      },
      {
        time: "14:00",
        name: { en: "Fuel and depart", ar: "التزود بالوقود والانطلاق" },
        note: {
          en: "Desert road back; ~3h to Cairo.",
          ar: "العودة عبر الطريق الصحراوي؛ حوالي ٣ ساعات إلى القاهرة.",
        },
      },
      {
        time: "17:00",
        name: { en: "Arrive Cairo", ar: "الوصول إلى القاهرة" },
        note: {
          en: "Return the car with the same fuel level you took it.",
          ar: "أعد السيارة بنفس مستوى الوقود الذي استلمتها به.",
        },
      },
    ],
    tips: [
      {
        en: "Alexandria parking is scarce — use the paid lots near the Citadel and Library.",
        ar: "مواقف السيارات نادرة في الإسكندرية — استخدم المواقف المدفوعة قرب القلعة والمكتبة.",
      },
      ...SHARED_TIPS.slice(0, 2),
      SHARED_TIPS[3],
    ],
  },

  "cairo>ain-sokhna": {
    outboundTitle: { en: "Cairo to Ain Sokhna", ar: "من القاهرة إلى العين السخنة" },
    exploreTitle: { en: "A day in Ain Sokhna", ar: "يوم في العين السخنة" },
    returnTitle: { en: "Back to Cairo", ar: "العودة إلى القاهرة" },
    outbound: [
      {
        time: "08:30",
        name: { en: "Depart via the Sokhna road", ar: "الانطلاق عبر طريق السخنة" },
        note: {
          en: "Just ~1.5–2h from Cairo — Egypt's easiest sea escape.",
          ar: "حوالي ساعة ونصف إلى ساعتين فقط من القاهرة — أسهل مهرب بحري في مصر.",
        },
      },
      {
        time: "09:45",
        name: { en: "Galala mountain viewpoint", ar: "إطلالة جبل الجلالة" },
        note: {
          en: "Pull over on the Galala plateau road for Red Sea views.",
          ar: "توقف على طريق هضبة الجلالة لمشاهدة البحر الأحمر.",
        },
      },
      {
        time: "10:30",
        name: { en: "Beach time", ar: "وقت الشاطئ" },
        note: {
          en: "Warm, calm water most of the year.",
          ar: "مياه دافئة وهادئة معظم أيام السنة.",
        },
      },
      {
        time: "14:00",
        name: { en: "Lunch at the marina", ar: "غداء في المارينا" },
        note: {
          en: "Fresh catch by the boats at Porto or La Vista bay.",
          ar: "سمك طازج بجوار المراكب في بورتو أو خليج لافيستا.",
        },
      },
      {
        time: "16:30",
        name: { en: "Porto Sokhna cable car", ar: "تلفريك بورتو السخنة" },
        note: {
          en: "Ride up the mountain for a sunset panorama.",
          ar: "اصعد الجبل لمشاهدة بانوراما الغروب.",
        },
      },
    ],
    explore: [
      {
        time: "09:00",
        name: { en: "Morning snorkeling", ar: "غطس صباحي بالأنبوب" },
        note: {
          en: "Rent gear on the beach; the reef is close to shore.",
          ar: "استأجر المعدات من الشاطئ؛ الشعاب قريبة من الساحل.",
        },
      },
      {
        time: "13:00",
        name: { en: "Seafood lunch", ar: "غداء بحري" },
        note: {
          en: "Grilled shrimp is the local specialty.",
          ar: "الجمبري المشوي هو الطبق المميز هنا.",
        },
      },
      {
        time: "17:00",
        name: { en: "Sunset walk on the sand", ar: "نزهة الغروب على الرمال" },
        note: {
          en: "The Galala mountains glow red behind you.",
          ar: "جبال الجلالة تتوهج بالأحمر خلفك.",
        },
      },
    ],
    inbound: [
      {
        time: "15:00",
        name: { en: "Late beach checkout", ar: "مغادرة متأخرة من الشاطئ" },
        note: {
          en: "Short drive means a full last day by the water.",
          ar: "قِصر الطريق يمنحك يومًا أخيرًا كاملًا على البحر.",
        },
      },
      {
        time: "16:00",
        name: { en: "Fuel at the Sokhna gate", ar: "التزود بالوقود عند بوابة السخنة" },
        note: {
          en: "Fill up before the desert stretch home.",
          ar: "املأ الخزان قبل الطريق الصحراوي للعودة.",
        },
      },
      {
        time: "18:00",
        name: { en: "Arrive Cairo", ar: "الوصول إلى القاهرة" },
        note: {
          en: "Aim to clear the Katameya interchange before dark.",
          ar: "احرص على تجاوز تقاطع القطامية قبل حلول الظلام.",
        },
      },
    ],
    tips: [
      {
        en: "Weekday trips beat the Thursday–Friday Sokhna traffic wave.",
        ar: "الرحلات في منتصف الأسبوع تتفادى موجة زحام السخنة يومي الخميس والجمعة.",
      },
      ...SHARED_TIPS.slice(0, 2),
      SHARED_TIPS[3],
    ],
  },

  "cairo>luxor": {
    outboundTitle: { en: "Cairo to Luxor", ar: "من القاهرة إلى الأقصر" },
    exploreTitle: { en: "A day among the temples", ar: "يوم بين المعابد" },
    returnTitle: { en: "Back to Cairo", ar: "العودة إلى القاهرة" },
    outbound: [
      {
        time: "05:30",
        name: { en: "Dawn departure via Sokhna", ar: "انطلاقة الفجر عبر السخنة" },
        note: {
          en: "The Red Sea route (Sokhna–Safaga–Qena) is ~8–9h; start early.",
          ar: "طريق البحر الأحمر (السخنة–سفاجا–قنا) يستغرق ٨–٩ ساعات؛ انطلق مبكرًا.",
        },
      },
      {
        time: "08:00",
        name: { en: "Zafarana rest stop", ar: "استراحة الزعفرانة" },
        note: {
          en: "Breakfast and fuel where the Gulf of Suez opens up.",
          ar: "إفطار ووقود حيث يتسع خليج السويس أمامك.",
        },
      },
      {
        time: "10:30",
        name: { en: "Safaga coffee and fuel", ar: "قهوة ووقود في سفاجا" },
        note: {
          en: "Last coastal stop before turning inland to Qena.",
          ar: "آخر توقف ساحلي قبل الاتجاه غربًا نحو قنا.",
        },
      },
      {
        time: "13:30",
        name: { en: "Dendera Temple of Hathor", ar: "معبد حتحور في دندرة" },
        note: {
          en: "One of Egypt's best-preserved temples, right off the Qena road.",
          ar: "من أفضل معابد مصر حفظًا، على مقربة من طريق قنا.",
        },
      },
      {
        time: "16:30",
        name: { en: "Arrive Luxor, sunset at Luxor Temple", ar: "الوصول إلى الأقصر وغروب عند معبد الأقصر" },
        note: {
          en: "The temple is magical as the lights come on.",
          ar: "المعبد ساحر لحظة إضاءة الأنوار.",
        },
      },
    ],
    explore: [
      {
        time: "06:00",
        name: { en: "Valley of the Kings", ar: "وادي الملوك" },
        note: {
          en: "Cross to the West Bank early to beat heat and crowds.",
          ar: "اعبر إلى البر الغربي مبكرًا لتفادي الحر والزحام.",
        },
      },
      {
        time: "10:00",
        name: { en: "Hatshepsut Temple", ar: "معبد حتشبسوت" },
        note: {
          en: "The terraces are stunning against the cliffs of Deir el-Bahari.",
          ar: "الشرفات مذهلة أمام جروف الدير البحري.",
        },
      },
      {
        time: "13:00",
        name: { en: "Lunch by the Nile", ar: "غداء على النيل" },
        note: {
          en: "Rest through the midday heat with a river view.",
          ar: "استرح وقت الظهيرة بإطلالة على النهر.",
        },
      },
      {
        time: "16:30",
        name: { en: "Karnak Temple", ar: "معبد الكرنك" },
        note: {
          en: "Give the hypostyle hall at least an hour.",
          ar: "امنح صالة الأعمدة الكبرى ساعة على الأقل.",
        },
      },
    ],
    inbound: [
      {
        time: "06:00",
        name: { en: "Early start north", ar: "انطلاقة مبكرة شمالًا" },
        note: {
          en: "Full tank in Luxor; retrace via Qena–Safaga.",
          ar: "خزان ممتلئ من الأقصر؛ العودة عبر قنا–سفاجا.",
        },
      },
      {
        time: "11:00",
        name: { en: "Ras Gharib rest stop", ar: "استراحة رأس غارب" },
        note: {
          en: "Stretch and refuel on the Red Sea coast.",
          ar: "استرح وتزود بالوقود على ساحل البحر الأحمر.",
        },
      },
      {
        time: "15:30",
        name: { en: "Arrive Cairo", ar: "الوصول إلى القاهرة" },
        note: {
          en: "Long day — split it with a Sokhna overnight if you can.",
          ar: "يوم طويل — قسّمه بمبيت في السخنة إن استطعت.",
        },
      },
    ],
    tips: [
      {
        en: "This is a serious long-distance drive — check tires and coolant before day one.",
        ar: "هذه رحلة طويلة حقًا — افحص الإطارات وسائل التبريد قبل اليوم الأول.",
      },
      {
        en: "Buy the Luxor West Bank tickets at the central office before driving to the sites.",
        ar: "اشترِ تذاكر البر الغربي من المكتب المركزي قبل التوجه إلى المواقع.",
      },
      ...SHARED_TIPS.slice(0, 2),
    ],
  },

  "giza>fayoum": {
    outboundTitle: { en: "Giza to Fayoum", ar: "من الجيزة إلى الفيوم" },
    exploreTitle: { en: "A day around the oasis", ar: "يوم حول الواحة" },
    returnTitle: { en: "Back to Giza", ar: "العودة إلى الجيزة" },
    outbound: [
      {
        time: "08:00",
        name: { en: "Depart via the Fayoum desert road", ar: "الانطلاق عبر طريق الفيوم الصحراوي" },
        note: {
          en: "~1.5h from Giza; fill the tank at the ring road exit.",
          ar: "حوالي ساعة ونصف من الجيزة؛ املأ الخزان عند مخرج الطريق الدائري.",
        },
      },
      {
        time: "09:45",
        name: { en: "Wadi El Rayan waterfalls", ar: "شلالات وادي الريان" },
        note: {
          en: "Egypt's only waterfalls, between two desert lakes.",
          ar: "الشلالات الوحيدة في مصر، بين بحيرتين صحراويتين.",
        },
      },
      {
        time: "11:30",
        name: { en: "Magic Lake sandboarding", ar: "التزلج على الرمال عند البحيرة المسحورة" },
        note: {
          en: "The dunes drop straight to the water — bring a board or rent one.",
          ar: "الكثبان تنحدر مباشرة نحو الماء — أحضر لوحًا أو استأجر واحدًا.",
        },
      },
      {
        time: "13:30",
        name: { en: "Lunch in Tunis Village", ar: "غداء في قرية تونس" },
        note: {
          en: "Pottery studios and farm-to-table food above Lake Qarun.",
          ar: "ورش الفخار وطعام من المزرعة مباشرة بإطلالة على بحيرة قارون.",
        },
      },
      {
        time: "15:30",
        name: { en: "Lake Qarun sunset", ar: "غروب بحيرة قارون" },
        note: {
          en: "Flamingo-spotting season runs through winter.",
          ar: "موسم مشاهدة طيور الفلامنجو يمتد طوال الشتاء.",
        },
      },
    ],
    explore: [
      {
        time: "09:00",
        name: { en: "Wadi El Hitan (Valley of the Whales)", ar: "وادي الحيتان" },
        note: {
          en: "UNESCO fossil site; a 4x4-friendly desert track.",
          ar: "موقع حفريات مسجل في اليونسكو؛ مسار صحراوي مناسب للدفع الرباعي.",
        },
      },
      {
        time: "13:00",
        name: { en: "Pottery workshop in Tunis Village", ar: "ورشة فخار في قرية تونس" },
        note: {
          en: "Try the wheel — studios welcome walk-ins.",
          ar: "جرّب عجلة الفخار — الورش ترحب بالزوار دون حجز.",
        },
      },
      {
        time: "16:00",
        name: { en: "Kayaking on Lake Qarun", ar: "التجديف في بحيرة قارون" },
        note: {
          en: "Calm late-afternoon water and desert light.",
          ar: "مياه هادئة في العصر وضوء صحراوي جميل.",
        },
      },
    ],
    inbound: [
      {
        time: "14:00",
        name: { en: "Last oasis lunch", ar: "غداء أخير في الواحة" },
        note: {
          en: "One more Tunis Village meal before heading out.",
          ar: "وجبة أخيرة في قرية تونس قبل الانطلاق.",
        },
      },
      {
        time: "15:30",
        name: { en: "Depart for Giza", ar: "الانطلاق نحو الجيزة" },
        note: {
          en: "Beat the sunset — the desert road is unlit.",
          ar: "انطلق قبل الغروب — الطريق الصحراوي غير مُضاء.",
        },
      },
      {
        time: "17:00",
        name: { en: "Arrive Giza", ar: "الوصول إلى الجيزة" },
        note: {
          en: "Shake the sand out before returning the car.",
          ar: "انفض الرمال عن السيارة قبل إعادتها.",
        },
      },
    ],
    tips: [
      {
        en: "The lake tracks get sandy — an SUV is ideal; sedans should stay on paved roads.",
        ar: "مسارات البحيرة رملية — السيارات الرباعية مثالية؛ على السيدان الالتزام بالطرق الممهدة.",
      },
      ...SHARED_TIPS.slice(1, 4),
    ],
  },

  "cairo>hurghada": {
    outboundTitle: { en: "Cairo to Hurghada", ar: "من القاهرة إلى الغردقة" },
    exploreTitle: { en: "A day on the Red Sea", ar: "يوم على البحر الأحمر" },
    returnTitle: { en: "Back to Cairo", ar: "العودة إلى القاهرة" },
    outbound: [
      {
        time: "06:30",
        name: { en: "Depart via the Sokhna road", ar: "الانطلاق عبر طريق السخنة" },
        note: {
          en: "~5h along the Red Sea coast; start early to arrive for lunch.",
          ar: "حوالي ٥ ساعات بمحاذاة البحر الأحمر؛ انطلق مبكرًا لتصل وقت الغداء.",
        },
      },
      {
        time: "08:30",
        name: { en: "Zafarana fuel and breakfast", ar: "وقود وإفطار في الزعفرانة" },
        note: {
          en: "Windfarm country — the gulf views begin here.",
          ar: "منطقة مزارع الرياح — تبدأ إطلالات الخليج من هنا.",
        },
      },
      {
        time: "10:30",
        name: { en: "Ras Gharib coffee stop", ar: "استراحة قهوة في رأس غارب" },
        note: {
          en: "Halfway marker; stretch before the final coastal run.",
          ar: "منتصف الطريق؛ استرح قبل المرحلة الساحلية الأخيرة.",
        },
      },
      {
        time: "12:30",
        name: { en: "Arrive Hurghada, marina lunch", ar: "الوصول إلى الغردقة وغداء في المارينا" },
        note: {
          en: "Fresh seafood overlooking the yachts.",
          ar: "مأكولات بحرية طازجة بإطلالة على اليخوت.",
        },
      },
      {
        time: "17:30",
        name: { en: "Sunset at the promenade", ar: "الغروب على الممشى" },
        note: {
          en: "Walk the Mamsha strip as the heat breaks.",
          ar: "تمشَّ في الممشى السياحي مع انكسار الحرارة.",
        },
      },
    ],
    explore: [
      {
        time: "08:30",
        name: { en: "Giftun Island boat trip", ar: "رحلة بحرية إلى جزيرة الجفتون" },
        note: {
          en: "Book a snorkeling day boat from the marina.",
          ar: "احجز مركب غطس ليوم كامل من المارينا.",
        },
      },
      {
        time: "15:00",
        name: { en: "Old Town (El Dahar) souq", ar: "سوق الدهار القديم" },
        note: {
          en: "Spices, shisha, and bargaining practice.",
          ar: "توابل وشيشة وفرصة للتدرب على الفصال.",
        },
      },
      {
        time: "19:00",
        name: { en: "Dinner at the marina", ar: "عشاء في المارينا" },
        note: {
          en: "Evening breeze and boats coming home.",
          ar: "نسيم المساء والمراكب العائدة إلى المرسى.",
        },
      },
    ],
    inbound: [
      {
        time: "07:00",
        name: { en: "Early departure north", ar: "انطلاقة مبكرة شمالًا" },
        note: {
          en: "Full tank; the coast road is fastest before 9am.",
          ar: "خزان ممتلئ؛ الطريق الساحلي أسرع قبل التاسعة صباحًا.",
        },
      },
      {
        time: "10:00",
        name: { en: "Zafarana rest stop", ar: "استراحة الزعفرانة" },
        note: {
          en: "Last proper services before the Sokhna junction.",
          ar: "آخر خدمات جيدة قبل مفترق السخنة.",
        },
      },
      {
        time: "12:30",
        name: { en: "Arrive Cairo", ar: "الوصول إلى القاهرة" },
        note: {
          en: "In before the afternoon ring road traffic.",
          ar: "الوصول قبل زحام الطريق الدائري بعد الظهر.",
        },
      },
    ],
    tips: [
      {
        en: "Strong crosswinds hit the Zafarana stretch — keep both hands on the wheel.",
        ar: "رياح جانبية قوية على امتداد الزعفرانة — أمسك المقود بكلتا يديك.",
      },
      ...SHARED_TIPS.slice(0, 3),
    ],
  },
};

/** Fill-in template for routes without curated data. */
function genericRoute(from: string, to: string): RouteDef {
  return {
    outboundTitle: { en: `${from} to ${to}`, ar: `من ${from} إلى ${to}` },
    exploreTitle: { en: `A day in ${to}`, ar: `يوم في ${to}` },
    returnTitle: { en: `Back to ${from}`, ar: `العودة إلى ${from}` },
    outbound: [
      {
        time: "08:00",
        name: { en: `Fuel up and depart ${from}`, ar: `التزود بالوقود والانطلاق من ${from}` },
        note: {
          en: "Full tank and tire check before the highway.",
          ar: "خزان ممتلئ وفحص للإطارات قبل الطريق السريع.",
        },
      },
      {
        time: "10:00",
        name: { en: "Highway rest stop", ar: "استراحة على الطريق السريع" },
        note: {
          en: "Coffee, restrooms, and a leg stretch at the midpoint.",
          ar: "قهوة ودورات مياه واستراحة قصيرة عند منتصف الطريق.",
        },
      },
      {
        time: "12:30",
        name: { en: `Arrive ${to} and check in`, ar: `الوصول إلى ${to} وتسجيل الدخول` },
        note: {
          en: "Drop your bags and get oriented.",
          ar: "ضع حقائبك وتعرّف على المكان.",
        },
      },
      {
        time: "14:00",
        name: { en: "Local lunch", ar: "غداء محلي" },
        note: {
          en: "Ask locals for the specialty of the region.",
          ar: "اسأل أهل المنطقة عن الأكلة المميزة عندهم.",
        },
      },
    ],
    explore: [
      {
        time: "09:30",
        name: { en: "Morning landmark visit", ar: "زيارة معلم صباحية" },
        note: {
          en: "Start with the area's main sight before it gets busy.",
          ar: "ابدأ بأشهر معالم المنطقة قبل الازدحام.",
        },
      },
      {
        time: "13:00",
        name: { en: "Lunch and rest", ar: "غداء واستراحة" },
        note: {
          en: "Sit out the midday heat.",
          ar: "تجنب حر الظهيرة بالراحة.",
        },
      },
      {
        time: "17:00",
        name: { en: "Sunset drive", ar: "جولة الغروب بالسيارة" },
        note: {
          en: "Explore the scenic roads in the golden hour.",
          ar: "استكشف الطرق الجميلة في الساعة الذهبية.",
        },
      },
    ],
    inbound: [
      {
        time: "11:00",
        name: { en: "Checkout and fuel", ar: "المغادرة والتزود بالوقود" },
        note: {
          en: "Top up before the return leg.",
          ar: "املأ الخزان قبل رحلة العودة.",
        },
      },
      {
        time: "13:00",
        name: { en: "Rest stop", ar: "استراحة" },
        note: {
          en: "Halfway break to stay sharp.",
          ar: "استراحة منتصف الطريق للحفاظ على التركيز.",
        },
      },
      {
        time: "15:30",
        name: { en: `Arrive ${from}`, ar: `الوصول إلى ${from}` },
        note: {
          en: "Return the car with a full tank.",
          ar: "أعد السيارة بخزان ممتلئ.",
        },
      },
    ],
    tips: SHARED_TIPS,
  };
}

/* ------------------------------------------------------------------ */
/* Local deterministic generator                                       */
/* ------------------------------------------------------------------ */

function normalizePlace(value: string): string {
  return value.trim().toLowerCase().replace(/\s+/g, "-");
}

function lookupRoute(from: string, to: string): RouteDef {
  const f = normalizePlace(from);
  const t = normalizePlace(to);
  // Giza departures share Cairo's highway network.
  const origins = f === "giza" ? [f, "cairo"] : f === "cairo" ? [f, "giza"] : [f];
  for (const origin of origins) {
    const route = ROUTES[`${origin}>${t}`];
    if (route) return route;
  }
  return genericRoute(from, to);
}

function tripDayCount(startDate: string, endDate: string): number {
  const start = new Date(`${startDate}T00:00:00`);
  const end = new Date(`${endDate}T00:00:00`);
  const diff = Math.round((end.getTime() - start.getTime()) / 86_400_000);
  return Math.min(7, Math.max(1, diff + 1));
}

function localizeStops(stops: StopDef[], language: ConciergeLanguage): ItineraryStop[] {
  return stops.map((s) => ({ time: s.time, name: s.name[language], note: s.note[language] }));
}

export function generateLocalItinerary(req: TripPlanRequest): Itinerary {
  const route = lookupRoute(req.from, req.to);
  const total = tripDayCount(req.startDate, req.endDate);
  const lang = req.language;

  const days: ItineraryDay[] = [
    { day: 1, title: route.outboundTitle[lang], stops: localizeStops(route.outbound, lang) },
  ];
  for (let d = 2; d < total; d++) {
    days.push({ day: d, title: route.exploreTitle[lang], stops: localizeStops(route.explore, lang) });
  }
  if (total >= 2) {
    days.push({ day: total, title: route.returnTitle[lang], stops: localizeStops(route.inbound, lang) });
  }

  return { days, tips: route.tips.map((tip) => tip[lang]) };
}

/* ------------------------------------------------------------------ */
/* Edge Function client with local fallback                            */
/* ------------------------------------------------------------------ */

function isItinerary(data: unknown): data is Itinerary {
  if (typeof data !== "object" || data === null) return false;
  const d = data as { days?: unknown; tips?: unknown };
  return (
    Array.isArray(d.days) &&
    d.days.length > 0 &&
    Array.isArray(d.tips) &&
    d.days.every(
      (day: unknown) =>
        typeof day === "object" &&
        day !== null &&
        typeof (day as ItineraryDay).title === "string" &&
        Array.isArray((day as ItineraryDay).stops),
    )
  );
}

async function fetchEdgeItinerary(
  req: TripPlanRequest,
  url: string,
  anonKey: string,
): Promise<Itinerary> {
  const res = await fetch(`${url.replace(/\/$/, "")}/functions/v1/trip-concierge`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${anonKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(req),
  });
  if (!res.ok) throw new Error(`trip-concierge responded ${res.status}`);
  const data: unknown = await res.json();
  if (!isItinerary(data)) throw new Error("trip-concierge returned an invalid itinerary");
  return data;
}

/**
 * Generate an itinerary. Uses the Supabase Edge Function when configured,
 * and always falls back to the local generator on any failure so the
 * feature works offline and without a backend.
 */
export async function generateItinerary(req: TripPlanRequest): Promise<TripPlanResult> {
  const url = import.meta.env.VITE_SUPABASE_URL as string | undefined;
  const anonKey = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;

  if (url && anonKey) {
    try {
      const itinerary = await fetchEdgeItinerary(req, url, anonKey);
      return { itinerary, source: "edge" };
    } catch {
      // Network/config/model failure — degrade to the local generator.
    }
  }
  return { itinerary: generateLocalItinerary(req), source: "local" };
}
